// ============================================================
//  FOURTH & FOREVER — names.js
//  DROP YOUR NAMES OBJECT HERE.
//  Must match this exact structure.
//  Save the file. Reload index.html. Done.
// ============================================================

const NAMES = {
 southeast: {
    first: {
      black: ["DeShawn","Malik","Trevon","Javion","Tre","Kylan","Darius","Jamal","Lamont","Terrell","Marquis","Jalen","DeAndre","Tyrese","JaQuan","LaShawn","Maurice","Jerome","Vernon","Curtis","Andre","Tyrone","Lamar","Quincy","Isaiah","Elijah","Gabriel","Levi","Zion","King","Prince","Messiah","Jeremiah","LeBron","Kobe","Jayden","Brayden","Aiden","Terrence","Marcus","Anthony","Kevin","Brandon","Justin","Tyler","Zachary","Austin","Dylan","Jordan","Cameron","Xavier","Desmond","Hakim","Rahim","Bilal","Kareem","Nadir","Aziz","Farid","Amir","Zahir","Zaire","Omari","Idris","Khalil","Tariq","Hassan","Musa","Ibrahim","Yusef","Ali","Ahmad"],
      white: ["Tucker","Colt","Beau","Tanner","Reid","Cade","Bo","Wyatt","Hunter","Chase","Blake","Cody","Brent","Shane","Kyle","Eric","Brian","Ryan","Jeremy","Nathan","Jeffrey","Stephen","Timothy","Kenneth","Ronald","Donald","Gary","Larry","Terry","Jerry","Barry","Harry","Perry","Murray","Corey","Rory","Felix","Oscar","Hugo","Louis","Pierre","Marcel","Henri","Rene","Claude","Jean","Marc","Philippe","Andre","Jacques","Francois","Michel","Bernard","Albert","Roger","Raymond","Gerard","Lawrence","Roland","Francis","Gregory","Dennis","Gerald","Raymond","Keith","Craig","Todd","Brett","Shawn","Derek","Wesley","Travis","Jared","Corey","Seth","Dustin","Cody","Brent","Shane"],
      hispanic: ["Santiago","Mateo","Leonardo","Sebastian","Diego","Thiago","Antonio","Luis","Carlos","Miguel","Angel","Jose","Daniel","Alejandro","Javier","Ivan","Eduardo","Ricardo","Andres","Julian","Fernando","Francisco","Manuel","Isaac","Emilio","Hector","Adrian","Gustavo","Raul","Sergio","Alberto","Mario","Oscar","Pedro","Jesus","Juan","Rafael","Rodrigo","Pablo","Enrique","Jorge","Ramon","Esteban","Ignacio","Vicente","Maximiliano","Nicolas","Agustin","Benito","Camilo","Cesar","Damian","Emiliano","Erick","Fabian","Gael","Gerardo","Gonzalo","Hilario","Ismael","Joaquin","Leandro","Luciano","Marcos","Martin","Matias","Mauricio","Maximo","Milton","Mirko","Nestor","Octavio","Oliver","Orlando","Pascual","Patricio","Rafael","Raul","Renato"],
      asian: ["Wei","Chen","Dong","Feng","Gang","Hai","Jian","Kai","Long","Ming","Nan","Qiang","Ren","Sheng","Tao","Wen","Arjun","Aryan","Dev","Rohan","Vihaan","Aditya","Krishna","Shaan","Reyansh","Hiroshi","Kenji","Satoshi","Takeshi","Yuki","Haruto","Sota","Riku","Kaito","Asahi","Ren","Akira","Joji","Taro","Ichiro","Jiro","Saburo","Shiro","Hachiro","Kuro","Midori","Ao","Aka","Kiiro","Murasaki","Dai","Sho","Kaz","Tad","Yas","Mas","Sus","Isa","Nob","Hide","Toshi","Katsu","Masa","Yoshi","Taka","Hiro","Mak","Osamu","Minoru","Shigeru","Eiji","Tetsu","Koji","Ryo","Ken","Shin","Jun","Toru","Hide","Koji","Ryo","Ken","Shin","Jun","Toru"],
      polynesian: ["Koa","Ikaika","Keanu","Lono","Makani","Nalu","Kaimana","Keoni","Kaelo","Kamali","Kane","Kanoa","Kekoa","Kelani","Keli","Kelo","Kema","Kemi","Keno","Keo","Kepa","Kera","Keri","Kero","Kesi","Keto","Keva","Kevi","Kewi","Keya","Keyo","Kian","Kiar","Kieb","Kief","Kien","Kier","Kies","Kiet","Kiew","Kifa","Kife","Kifo","Kiga","Kige","Kigo","Kigu","Kila","Kilo","Kimi","Kino","Kio","Kipa","Kipo","Kira","Kiro","Kisa","Kiso","Kita","Kito","Kiva","Kivo","Kiwa","Kiwi","Koa","Koba","Koda","Kodi","Kody","Kola","Kole","Koli","Kolo","Koma","Kome","Komi","Komo"]
    },
    last: {
      black: ["Washington","Jefferson","Jackson","Williams","Brown","Davis","Johnson","Jones","Harris","Robinson","Thompson","Moore","Taylor","Anderson","Thomas","White","Martin","Clark","Lewis","Walker","Hall","Allen","Young","King","Wright","Scott","Green","Baker","Adams","Nelson","Carter","Mitchell","Perez","Roberts","Turner","Phillips","Campbell","Parker","Evans","Edwards","Collins","Stewart","Sanchez","Morris","Rogers","Reed","Cook","Morgan","Bell","Murphy","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Torres","Peterson","Gray","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell"],
      white: ["Smith","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Hayes","Myers","Ford","Hamilton","Graham","Sullivan","Wallace","Woods","Cole","West","Jordan","Owens","Reynolds","Fisher","Ellis","Harrison","Gibson","Mcdonald","Cruz","Marshall","Ortiz","Gomez","Freeman","Wells","Webb","Simpson","Stevens","Tucker","Porter","Hunter","Hicks","Crawford","Shaw","Holmes","Rice","Robertson","Hunt","Black","Daniels","Palmer","Mills","Nichols","Grant","Knight","Ferguson","Rose","Stone","Hawkins","Dunn","Perkins","Hudson","Spencer","Carroll","Hansen","Castro","Hoffman","Hart","Elliott","Cunningham","Bradley","Dean","Hanson","Garza","Harvey","Little","Burton","Stanley"],
      hispanic: ["Martinez","Rodriguez","Flores","Gonzalez","Hernandez","Lopez","Perez","Sanchez","Ramirez","Torres","Rivera","Gomez","Diaz","Cruz","Reyes","Morales","Gutierrez","Ortiz","Ruiz","Castillo","Ramos","Chavez","Vargas","Mendoza","Silva","Romero","Juarez","Aguilar","Herrera","Medina","Contreras","Vega","Santos","Guerrero","Estrada","Delgado","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson"],
      asian: ["Wang","Li","Zhang","Liu","Chen","Yang","Huang","Zhao","Wu","Zhou","Xu","Sun","Ma","Zhu","Hu","Guo","Lin","He","Gao","Zheng","Kim","Lee","Park","Choi","Jung","Kang","Cho","Shin","Kwon","Hwang","Yoon","Jang","Song","Jeon","Han","Oh","Seo","Bae","Nam","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai"],
      polynesian: ["Ferguson","Rose","Stone","Hawkins","Dunn","Perkins","Hudson","Spencer","Carroll","Hansen","Castro","Hoffman","Hart","Elliott","Cunningham","Bradley","Dean","Hanson","Garza","Harvey","Little","Burton","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Guerrero"]
    }
  },
  southwest: {
    first: {
      black: ["DaQuan","Von","Ishmael","Rahim","Bilal","Kareem","Hakim","Nadir","Aziz","Farid","Amir","Zahir","Zaire","Omari","Idris","Khalil","Tariq","Hassan","Musa","Ibrahim","Yusef","Ali","Ahmad","Mohamed","Mustafa","Karim","Selim","Rashid","Dante","Vaughn","Lamon","Rickey","Benny","Fred","Earl","Louis","Leon","Clarence","Curtis","Jerome","Rodney","Glenn","Wayne","Douglas","Russell","Eugene","Vincent","Harold","Ralph","Henry","Arthur","George","Edward","Robert","James","William","David","Michael","Christopher","Daniel","Matthew","Andrew","Joseph","Levi","Samuel","Benjamin","Lucas","Henry","Alexander","Mason","Michael","Ethan","Jacob","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi"],
      white: ["Colton","Hunter","Chase","Blake","Tanner","Cody","Dustin","Travis","Brent","Shane","Kyle","Eric","Brian","Jason","Ryan","Jeremy","Adam","Nathan","Jeffrey","Stephen","Timothy","Kenneth","Ronald","Donald","Gary","Larry","Terry","Jerry","Barry","Harry","Perry","Murray","Corey","Rory","Felix","Oscar","Hugo","Louis","Pierre","Marcel","Henri","Rene","Claude","Jean","Marc","Philippe","Andre","Jacques","Francois","Michel","Bernard","Albert","Roger","Raymond","Gerard","Lawrence","Roland","Francis","Gregory","Dennis","Gerald","Keith","Craig","Todd","Brett","Shawn","Derek","Wesley","Travis","Jared","Corey","Seth","Dustin","Cody","Brent","Shane","Kyle","Eric","Brian","Jason","Ryan","Jeremy","Adam","Nathan"],
      hispanic: ["Santiago","Mateo","Leonardo","Sebastian","Diego","Thiago","Gabriel","Antonio","Luis","Carlos","Miguel","Angel","David","Jose","Daniel","Alejandro","Javier","Ivan","Eduardo","Ricardo","Andres","Julian","Fernando","Francisco","Manuel","Isaac","Emilio","Hector","Adrian","Gustavo","Raul","Sergio","Alberto","Mario","Oscar","Pedro","Jesus","Juan","Rafael","Rodrigo","Pablo","Enrique","Jorge","Ramon","Esteban","Ignacio","Vicente","Maximiliano","Nicolas","Agustin","Benito","Camilo","Cesar","Damian","Emiliano","Erick","Fabian","Gael","Gerardo","Gonzalo","Hilario","Ismael","Joaquin","Leandro","Luciano","Marcos","Martin","Matias","Mauricio","Maximo","Milton","Mirko","Nestor","Octavio","Oliver","Orlando","Pascual","Patricio","Rafael","Raul","Renato","Ricardo","Roberto","Rodrigo"],
      asian: ["Rohan","Vihaan","Aditya","Krishna","Shaan","Reyansh","Liam","Noah","Oliver","Elijah","William","James","Benjamin","Lucas","Henry","Alexander","Mason","Michael","Ethan","Daniel","Jacob","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi","David","John","Wyatt","Robert","Gabriel","Theodore","Caleb","Ryan","Christopher","Leo","Isaac","Jayden","Joshua","Andrew","Linus","Silas","Arthur","Charles","Thomas","Edward","Alfred","Harold","Frank","Raymond","Oliver","Elijah","William","James","Benjamin","Lucas","Henry","Alexander","Mason","Michael","Ethan","Daniel","Jacob","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi","David","John","Wyatt","Robert"],
      polynesian: ["Maverick","Zion","Kyler","Brayden","Ashton","Ryder","Rowan","Axel","Easton","Cooper","Hunter","Cayden","Nolan","Roman","Bryson","Greyson","Carson","Beckett","Leonardo","Vincent","Arthur","Miles","Theo","Xavier","Sawyer","Calvin","Silas","Koa","Ikaika","Keanu","Lono","Makani","Nalu","Kaimana","Keoni","Kaelo","Kamali","Kane","Kanoa","Kekoa","Kelani","Keli","Kelo","Kema","Kemi","Keno","Keo","Kepa","Kera","Keri","Kero","Kesi","Keto","Keva","Kevi","Kewi","Keya","Keyo","Kian","Kiar","Kieb","Kief","Kien","Kier","Kies","Kiet","Kiew","Kifa","Kife","Kifo","Kiga","Kige","Kigo","Kigu","Kila","Kilo","Kimi","Kino","Kio","Kipa","Kipo","Kira","Kiro"]
    },
    last: {
      black: ["Jefferson","Jackson","Williams","Brown","Davis","Johnson","Jones","Harris","Robinson","Thompson","Moore","Taylor","Anderson","Thomas","White","Martin","Clark","Lewis","Walker","Hall","Allen","Young","King","Wright","Scott","Green","Baker","Adams","Nelson","Carter","Mitchell","Perez","Roberts","Turner","Phillips","Campbell","Parker","Evans","Edwards","Collins","Stewart","Sanchez","Morris","Rogers","Reed","Cook","Morgan","Bell","Murphy","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Torres","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Hayes","Myers","Ford","Hamilton"],
      white: ["Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Rogers","Reed","Cook","Morgan","Bell","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry"],
      hispanic: ["Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Perez","Sanchez","Ramirez","Torres","Flores","Rivera","Gomez","Diaz","Cruz","Reyes","Morales","Gutierrez","Ortiz","Ruiz","Castillo","Ramos","Chavez","Vargas","Mendoza","Silva","Romero","Juarez","Aguilar","Herrera","Medina","Contreras","Vega","Santos","Guerrero","Estrada","Delgado","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena"],
      asian: ["Li","Zhang","Liu","Chen","Yang","Huang","Zhao","Wu","Zhou","Xu","Sun","Ma","Zhu","Hu","Guo","Lin","He","Gao","Zheng","Kim","Lee","Park","Choi","Jung","Kang","Cho","Shin","Kwon","Hwang","Yoon","Jang","Song","Jeon","Han","Oh","Seo","Bae","Nam","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh"],
      polynesian: ["Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Rogers","Reed","Cook","Morgan","Bell","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson"]
    }
  },
  midwest: {
    first: {
      black: ["DeShawn","Malik","Jamal","Tyrone","Lamar","Terrell","Darius","Marquis","Jalen","DeAndre","Tyrese","JaQuan","LaShawn","Maurice","Jerome","Vernon","Curtis","Andre","Quincy","Isaiah","Elijah","Gabriel","Levi","Zion","King","Prince","Messiah","Jeremiah","LeBron","Kobe","Jayden","Brayden","Aiden","Terrence","Marcus","Anthony","Kevin","Brandon","Justin","Tyler","Zachary","Austin","Dylan","Jordan","Cameron","Xavier","Desmond","Hakim","Rahim","Bilal","Kareem","Nadir","Aziz","Farid","Amir","Zahir","Zaire","Omari","Idris","Khalil","Tariq","Hassan","Musa","Ibrahim","Yusef","Ali","Ahmad","Mohamed","Mustafa","Karim","Selim","Rashid","Dante","Vaughn","Lamon","Rickey","Benny","Fred","Earl","Louis","Leon","Clarence"],
      white: ["Liam","Noah","Oliver","Elijah","William","James","Benjamin","Lucas","Henry","Alexander","Mason","Michael","Ethan","Daniel","Jacob","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi","David","John","Wyatt","Robert","Gabriel","Theodore","Caleb","Ryan","Christopher","Leo","Isaac","Jayden","Joshua","Andrew","Linus","Silas","Arthur","Charles","Thomas","Edward","George","Alfred","Harold","Frank","Raymond","Gregory","Dennis","Gerald","Keith","Craig","Todd","Brett","Shawn","Derek","Wesley","Travis","Jared","Corey","Seth","Dustin","Cody","Brent","Shane","Kyle","Eric","Brian","Jason","Ryan","Jeremy","Adam","Nathan","Jeffrey","Stephen","Timothy","Kenneth","Ronald","Donald","Gary","Larry","Terry","Jerry","Barry","Harry","Perry","Murray","Corey","Rory","Felix","Oscar"],
      hispanic: ["Santiago","Mateo","Leonardo","Sebastian","Diego","Thiago","Gabriel","Antonio","Luis","Carlos","Miguel","Angel","David","Jose","Daniel","Alejandro","Javier","Ivan","Eduardo","Ricardo","Andres","Julian","Fernando","Francisco","Manuel","Isaac","Emilio","Hector","Adrian","Gustavo","Raul","Sergio","Alberto","Mario","Oscar","Pedro","Jesus","Juan","Rafael","Rodrigo","Pablo","Enrique","Jorge","Ramon","Esteban","Ignacio","Vicente","Maximiliano","Nicolas","Agustin","Benito","Camilo","Cesar","Damian","Emiliano","Erick","Fabian","Gael","Gerardo","Gonzalo","Hilario","Ismael","Joaquin","Leandro","Luciano","Marcos","Martin","Matias","Mauricio","Maximo","Milton","Mirko","Nestor","Octavio","Oliver","Orlando","Pascual","Patricio","Rafael","Raul","Renato","Ricardo","Roberto","Rodrigo","Rogelio","Roman","Ruben","Salvador","Samuel","Santiago","Saul","Sebastian","Sergio","Severiano"],
      asian: ["Arjun","Aryan","Dev","Rohan","Vihaan","Aditya","Krishna","Shaan","Reyansh","Wei","Chen","Dong","Feng","Gang","Hai","Jian","Kai","Long","Ming","Nan","Qiang","Ren","Sheng","Tao","Wen","Hiroshi","Kenji","Satoshi","Takeshi","Yuki","Haruto","Sota","Riku","Kaito","Asahi","Ren","Akira","Joji","Taro","Ichiro","Jiro","Saburo","Shiro","Hachiro","Kuro","Midori","Ao","Aka","Kiiro","Murasaki","Dai","Sho","Kaz","Tad","Yas","Mas","Sus","Isa","Nob","Hide","Toshi","Katsu","Masa","Yoshi","Taka","Hiro","Mak","Osamu","Minoru","Shigeru","Eiji","Tetsu","Koji","Ryo","Ken","Shin","Jun","Toru","Hide","Koji","Ryo","Ken","Shin","Jun","Toru","Hide","Koji","Ryo","Ken","Shin","Jun"],
      polynesian: ["Kai","Koa","Jaxon","Maverick","Zion","Kyler","Brayden","Ashton","Ryder","Rowan","Axel","Easton","Cooper","Hunter","Cayden","Nolan","Roman","Bryson","Greyson","Carson","Beckett","Leonardo","Vincent","Arthur","Miles","Theo","Xavier","Sawyer","Calvin","Silas","Ikaika","Keanu","Lono","Makani","Nalu","Kaimana","Keoni","Kaelo","Kamali","Kane","Kanoa","Kekoa","Kelani","Keli","Kelo","Kema","Kemi","Keno","Keo","Kepa","Kera","Keri","Kero","Kesi","Keto","Keva","Kevi","Kewi","Keya","Keyo","Kian","Kiar","Kieb","Kief","Kien","Kier","Kies","Kiet","Kiew","Kifa","Kife","Kifo","Kiga","Kige","Kigo","Kigu","Kila","Kilo","Kimi","Kino","Kio","Kipa","Kipo","Kira","Kiro","Kisa","Kiso","Kita","Kito","Kiva","Kivo","Kiwa","Kiwi"]
    },
    last: {
      black: ["Washington","Jefferson","Jackson","Williams","Brown","Davis","Johnson","Jones","Harris","Robinson","Thompson","Moore","Taylor","Anderson","Thomas","White","Martin","Clark","Lewis","Walker","Hall","Allen","Young","King","Wright","Scott","Green","Baker","Adams","Nelson","Carter","Mitchell","Perez","Roberts","Turner","Phillips","Campbell","Parker","Evans","Edwards","Collins","Stewart","Sanchez","Morris","Rogers","Reed","Cook","Morgan","Bell","Murphy","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Torres","Peterson","Gray","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Hayes","Myers","Ford","Hamilton"],
      white: ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Rogers","Reed","Cook","Morgan","Bell","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell"],
      hispanic: ["Martinez","Rodriguez","Flores","Gonzalez","Hernandez","Lopez","Perez","Sanchez","Ramirez","Torres","Rivera","Gomez","Diaz","Cruz","Reyes","Morales","Gutierrez","Ortiz","Ruiz","Castillo","Ramos","Chavez","Vargas","Mendoza","Silva","Romero","Juarez","Aguilar","Herrera","Medina","Contreras","Vega","Santos","Guerrero","Estrada","Delgado","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena"],
      asian: ["Wang","Li","Zhang","Liu","Chen","Yang","Huang","Zhao","Wu","Zhou","Xu","Sun","Ma","Zhu","Hu","Guo","Lin","He","Gao","Zheng","Kim","Lee","Park","Choi","Jung","Kang","Cho","Shin","Kwon","Hwang","Yoon","Jang","Song","Jeon","Han","Oh","Seo","Bae","Nam","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh"],
      polynesian: ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Rogers","Reed","Cook","Morgan","Bell","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson"]
    }
  },
  northeast: {
    first: {
      black: ["Jamal","Quincy","Tyrese","Malik","DeShawn","Trevon","Javion","Tre","Kylan","Darius","Lamont","Terrell","Marquis","Jalen","DeAndre","Maurice","Jerome","Vernon","Curtis","Andre","Tyrone","Lamar","Isaiah","Elijah","Gabriel","Levi","Zion","King","Prince","Messiah","Jeremiah","LeBron","Kobe","Jayden","Brayden","Aiden","Terrence","Marcus","Anthony","Kevin","Brandon","Justin","Tyler","Zachary","Austin","Dylan","Jordan","Cameron","Xavier","Desmond","Hakim","Rahim","Bilal","Kareem","Nadir","Aziz","Farid","Amir","Zahir","Zaire","Omari","Idris","Khalil","Tariq","Hassan","Musa","Ibrahim","Yusef","Ali","Ahmad","Mohamed","Mustafa","Karim","Selim","Rashid","Dante","Vaughn","Lamon","Rickey","Benny","Fred","Earl","Louis","Leon"],
      white: ["Luca","Giovanni","Anthony","Salvatore","Dominic","Frank","Vincent","Paul","Robert","Michael","Christopher","Stephen","Thomas","Daniel","Matthew","Andrew","Joseph","David","Richard","Charles","Sean","Patrick","Brendan","Connor","Liam","Declan","Finn","Owen","Riley","Murphy","James","William","John","Jack","Henry","George","Edward","Arthur","Alfred","Harold","Jacob","Isaac","Adam","Noah","Samuel","Benjamin","Aaron","Joshua","Caleb","Ethan","Gabriel","Raphael","Solomon","Moshe","Aryeh","Chaim","Yitzchak","Liam","Noah","Oliver","Elijah","William","James","Benjamin","Lucas","Henry","Alexander","Mason","Michael","Ethan","Daniel","Jacob","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi","David","John","Wyatt","Robert"],
      hispanic: ["Marco","Diego","Luis","Carlos","Santiago","Mateo","Leonardo","Sebastian","Thiago","Gabriel","Antonio","Angel","David","Jose","Daniel","Alejandro","Javier","Ivan","Eduardo","Ricardo","Andres","Julian","Fernando","Francisco","Manuel","Isaac","Emilio","Hector","Adrian","Gustavo","Raul","Sergio","Alberto","Mario","Oscar","Pedro","Jesus","Juan","Rafael","Rodrigo","Pablo","Enrique","Jorge","Ramon","Esteban","Ignacio","Vicente","Maximiliano","Nicolas","Agustin","Benito","Camilo","Cesar","Damian","Emiliano","Erick","Fabian","Gael","Gerardo","Gonzalo","Hilario","Ismael","Joaquin","Leandro","Luciano","Marcos","Martin","Matias","Mauricio","Maximo","Milton","Mirko","Nestor","Octavio","Oliver","Orlando","Pascual","Patricio","Rafael","Raul","Renato","Ricardo","Roberto","Rodrigo","Rogelio","Roman","Ruben","Salvador","Samuel","Santiago","Saul","Sebastian","Sergio"],
      asian: ["Wei","Jing","Lan","Hui","Fang","Yan","Li","Xiu","Min","Sun","Yue","Hong","Ping","Qing","Xia","Ying","Zhen","An","Bo","Chen","Dong","Feng","Gang","Hai","Jian","Kai","Long","Ming","Nan","Qiang","Ren","Sheng","Tao","Wen","Arjun","Aryan","Dev","Rohan","Vihaan","Aditya","Krishna","Shaan","Reyansh","Hiroshi","Kenji","Satoshi","Takeshi","Yuki","Haruto","Sota","Riku","Kaito","Asahi","Ren","Akira","Joji","Taro","Ichiro","Jiro","Saburo","Shiro","Hachiro","Kuro","Midori","Ao","Aka","Kiiro","Murasaki","Dai","Sho","Kaz","Tad","Yas","Mas","Sus","Isa","Nob","Hide","Toshi","Katsu","Masa","Yoshi","Taka","Hiro","Mak","Osamu","Minoru","Shigeru","Eiji","Tetsu","Koji","Ryo","Ken","Shin","Jun","Toru"],
      polynesian: ["Jaxon","Maverick","Zion","Kyler","Brayden","Ashton","Ryder","Rowan","Axel","Easton","Cooper","Hunter","Cayden","Nolan","Roman","Bryson","Greyson","Carson","Beckett","Leonardo","Vincent","Arthur","Miles","Theo","Xavier","Sawyer","Calvin","Silas","Koa","Ikaika","Keanu","Lono","Makani","Nalu","Kaimana","Keoni","Kaelo","Kamali","Kane","Kanoa","Kekoa","Kelani","Keli","Kelo","Kema","Kemi","Keno","Keo","Kepa","Kera","Keri","Kero","Kesi","Keto","Keva","Kevi","Kewi","Keya","Keyo","Kian","Kiar","Kieb","Kief","Kien","Kier","Kies","Kiet","Kiew","Kifa","Kife","Kifo","Kiga","Kige","Kigo","Kigu","Kila","Kilo","Kimi","Kino","Kio","Kipa","Kipo","Kira","Kiro","Kisa","Kiso","Kita","Kito","Kiva","Kivo","Kiwa"]
    },
    last: {
      black: ["Jefferson","Jackson","Williams","Brown","Davis","Johnson","Jones","Harris","Robinson","Thompson","Moore","Taylor","Anderson","Thomas","White","Martin","Clark","Lewis","Walker","Hall","Allen","Young","King","Wright","Scott","Green","Baker","Adams","Nelson","Carter","Mitchell","Perez","Roberts","Turner","Phillips","Campbell","Parker","Evans","Edwards","Collins","Stewart","Sanchez","Morris","Rogers","Reed","Cook","Morgan","Bell","Murphy","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Torres","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Hayes","Myers","Ford","Hamilton"],
      white: ["Rossi","Russo","Ferrara","Esposito","Romano","Colombo","Ricci","Marino","Greco","Bruno","Gallo","Conti","De Luca","Mancini","Costa","Giordano","Rizzo","Lombardi","Moretti","Barbieri","Fontana","Santoro","Caruso","Marchetti","Murphy","Kelly","Byrne","Walsh","OConnor","Lynch","Griffin","Hayes","McCarthy","OBrien","Ryan","OReilly","Doyle","Murray","Brennan","Quinn","Moore","Fitzgerald","OSullivan","Flanagan","Kavanagh","Sweeney","Powers","ONeill","Donnelly","Cohen","Levy","Goldstein","Rosenberg","Friedman","Kaplan","Silver","Bernstein","Weiss","Hoffman","Schwartz","Stein","Adler","Goldberg","Gross","Katz","Klein","Levin","Meyer","Roth","Sachs","Schulman","Shapiro","Stern","Wolf","Silva","Santos","Ferreira","Pereira","Oliveira","Costa","Rodrigues","Martins","Jesus","Sousa","Fernandes"],
      hispanic: ["Garcia","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Perez","Sanchez","Ramirez","Torres","Flores","Rivera","Gomez","Diaz","Cruz","Reyes","Morales","Gutierrez","Ortiz","Ruiz","Castillo","Ramos","Chavez","Vargas","Mendoza","Silva","Romero","Juarez","Aguilar","Herrera","Medina","Contreras","Vega","Santos","Guerrero","Estrada","Delgado","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena"],
      asian: ["Zhang","Liu","Chen","Yang","Huang","Zhao","Wu","Zhou","Xu","Sun","Ma","Zhu","Hu","Guo","Lin","He","Gao","Zheng","Kim","Lee","Park","Choi","Jung","Kang","Cho","Shin","Kwon","Hwang","Yoon","Jang","Song","Jeon","Han","Oh","Seo","Bae","Nam","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu"],
      polynesian: ["Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Rogers","Reed","Cook","Morgan","Bell","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores"]
    }
  },
  west: {
    first: {
      black: ["Marquis","Jalen","DeAndre","Tyrese","JaQuan","LaShawn","Maurice","Jerome","Vernon","Curtis","Andre","Tyrone","Lamar","Quincy","Isaiah","Elijah","Gabriel","Levi","Zion","King","Prince","Messiah","Jeremiah","LeBron","Kobe","Jayden","Brayden","Aiden","Terrence","Marcus","Anthony","Kevin","Brandon","Justin","Tyler","Zachary","Austin","Dylan","Jordan","Cameron","Xavier","Desmond","Hakim","Rahim","Bilal","Kareem","Nadir","Aziz","Farid","Amir","Zahir","Zaire","Omari","Idris","Khalil","Tariq","Hassan","Musa","Ibrahim","Yusef","Ali","Ahmad","Mohamed","Mustafa","Karim","Selim","Rashid","Dante","Vaughn","Lamon","Rickey","Benny","Fred","Earl","Louis","Leon","Clarence","Curtis","Jerome","Rodney","Glenn","Wayne","Douglas","Russell","Eugene","Vincent","Harold","Ralph","Henry","Arthur","George"],
      white: ["Mason","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi","David","John","Wyatt","Robert","Gabriel","Theodore","Caleb","Ryan","Christopher","Leo","Isaac","Jayden","Joshua","Andrew","Linus","Silas","Arthur","Charles","Thomas","Edward","George","Alfred","Harold","Frank","Raymond","Oliver","Elijah","William","James","Benjamin","Lucas","Henry","Alexander","Mason","Michael","Ethan","Daniel","Jacob","Logan","Jackson","Sebastian","Jack","Aiden","Owen","Samuel","Matthew","Joseph","Levi","David","John","Wyatt","Robert","Gabriel","Theodore","Caleb","Ryan","Christopher","Leo","Isaac","Jayden","Joshua","Andrew","Linus","Silas","Arthur","Charles","Thomas","Edward","George","Alfred","Harold","Frank","Raymond","Gregory","Dennis","Gerald","Keith","Craig","Todd","Brett","Shawn","Derek","Wesley","Travis","Jared"],
      hispanic: ["Santiago","Mateo","Leonardo","Sebastian","Diego","Thiago","Gabriel","Antonio","Luis","Carlos","Miguel","Angel","David","Jose","Daniel","Alejandro","Javier","Ivan","Eduardo","Ricardo","Andres","Julian","Fernando","Francisco","Manuel","Isaac","Emilio","Hector","Adrian","Gustavo","Raul","Sergio","Alberto","Mario","Oscar","Pedro","Jesus","Juan","Rafael","Rodrigo","Pablo","Enrique","Jorge","Ramon","Esteban","Ignacio","Vicente","Maximiliano","Nicolas","Agustin","Benito","Camilo","Cesar","Damian","Emiliano","Erick","Fabian","Gael","Gerardo","Gonzalo","Hilario","Ismael","Joaquin","Leandro","Luciano","Marcos","Martin","Matias","Mauricio","Maximo","Milton","Mirko","Nestor","Octavio","Oliver","Orlando","Pascual","Patricio","Rafael","Raul","Renato","Ricardo","Roberto","Rodrigo","Rogelio","Roman","Ruben","Salvador","Samuel","Santiago","Saul","Sebastian","Sergio","Severiano","Silvestre","Teodoro","Tomas","Valentin","Victor"],
      asian: ["Kenji","Hiroshi","Satoshi","Takeshi","Yuki","Haruto","Sota","Riku","Kaito","Asahi","Ren","Akira","Joji","Taro","Ichiro","Jiro","Saburo","Shiro","Hachiro","Kuro","Dai","Sho","Kaz","Tad","Yas","Mas","Sus","Isa","Nob","Hide","Toshi","Katsu","Masa","Yoshi","Taka","Hiro","Mak","Osamu","Minoru","Shigeru","Eiji","Tetsu","Koji","Ryo","Ken","Shin","Jun","Toru","Hide","Koji","Ryo","Ken","Shin","Jun","Toru","Hide","Koji","Ryo","Ken","Shin","Jun","Toru","Hide","Koji","Ryo","Ken","Shin","Jun","Toru","Wei","Chen","Dong","Feng","Gang","Hai","Jian","Kai","Long","Ming","Nan","Qiang","Ren","Sheng","Tao","Wen","Arjun","Aryan","Dev","Rohan","Vihaan","Aditya","Krishna","Shaan","Reyansh"],
      polynesian: ["Kai","Koa","Jaxon","Maverick","Zion","Kyler","Brayden","Ashton","Ryder","Rowan","Axel","Easton","Cooper","Hunter","Cayden","Nolan","Roman","Bryson","Greyson","Carson","Beckett","Leonardo","Vincent","Arthur","Miles","Theo","Xavier","Sawyer","Calvin","Silas","Ikaika","Keanu","Lono","Makani","Nalu","Kaimana","Keoni","Kaelo","Kamali","Kane","Kanoa","Kekoa","Kelani","Keli","Kelo","Kema","Kemi","Keno","Keo","Kepa","Kera","Keri","Kero","Kesi","Keto","Keva","Kevi","Kewi","Keya","Keyo","Kian","Kiar","Kieb","Kief","Kien","Kier","Kies","Kiet","Kiew","Kifa","Kife","Kifo","Kiga","Kige","Kigo","Kigu","Kila","Kilo","Kimi","Kino","Kio","Kipa","Kipo","Kira","Kiro","Kisa","Kiso","Kita","Kito","Kiva","Kivo","Kiwa","Kiwi"]
    },
    last: {
      black: ["James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Hayes","Myers","Ford","Hamilton","Graham","Sullivan","Wallace","Woods","Cole","West","Jordan","Owens","Reynolds","Fisher","Ellis","Harrison","Gibson","Mcdonald","Cruz","Marshall","Ortiz","Gomez","Freeman","Wells","Webb","Simpson","Stevens","Tucker","Porter","Hunter","Hicks","Crawford","Henry","Boyd","Mason","Morales","Kennedy","Warren","Dixon","Ramos","Reyes","Burns","Gordon","Shaw","Holmes","Rice","Robertson","Hunt","Black","Daniels","Palmer","Mills","Nichols","Grant","Knight","Ferguson","Rose","Stone","Hawkins","Dunn","Perkins","Hudson","Spencer","Carroll","Hansen","Castro","Hoffman","Hart","Elliott","Cunningham"],
      white: ["Morris","Rogers","Reed","Cook","Morgan","Bell","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Hayes","Myers","Ford","Hamilton","Graham","Sullivan","Wallace","Woods","Cole","West","Jordan","Owens","Reynolds","Fisher","Ellis","Harrison","Gibson","Mcdonald","Cruz","Marshall","Ortiz","Gomez","Freeman","Wells","Webb","Simpson","Stevens","Tucker","Porter","Hunter","Hicks","Crawford","Henry","Boyd","Mason","Morales","Kennedy","Warren","Dixon","Ramos","Reyes","Burns","Gordon","Shaw","Holmes","Rice","Robertson","Hunt","Black","Daniels","Palmer","Mills","Nichols","Grant","Knight","Ferguson"],
      hispanic: ["Montgomery","Harvey","Oliver","Howell","Dean","Hanson","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena","Rios","Douglas","Sandoval","Barrett","Hopkins","Keller","Guerrero","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman","Davidson","May","Day","Schneider","Newman","Brewer","Lucas","Holland","Wong","Banks","Santos","Curtis","Pearson","Delgado","Valdez","Pena"],
      asian: ["Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Wang","Li","Zhang","Liu","Chen","Yang","Huang","Zhao","Wu","Zhou","Xu","Sun","Ma","Zhu","Hu","Guo","Lin","He","Gao","Zheng","Kim","Lee","Park","Choi","Jung","Kang","Cho","Shin","Kwon","Hwang","Yoon","Jang","Song","Jeon","Han","Oh","Seo","Bae","Nam","Nguyen","Tran","Le","Pham","Hoang","Huynh","Phan","Vu","Dang","Bui","Do","Dinh","Cao","Truong","Lam","Vo","Ly","Mai","Tang","Ngo","Quach","Luong","Ha","Lai","Trinh","Duong","Bui","Nguyen","Tran","Le","Pham","Hoang","Huynh"],
      polynesian: ["Gibson","Mcdonald","Cruz","Marshall","Ortiz","Gomez","Freeman","Wells","Webb","Simpson","Stevens","Tucker","Porter","Hunter","Hicks","Crawford","Henry","Boyd","Mason","Morales","Kennedy","Warren","Dixon","Ramos","Reyes","Burns","Gordon","Shaw","Holmes","Rice","Robertson","Hunt","Black","Daniels","Palmer","Mills","Nichols","Grant","Knight","Ferguson","Rose","Stone","Hawkins","Dunn","Perkins","Hudson","Spencer","Carroll","Hansen","Castro","Hoffman","Hart","Elliott","Cunningham","Bradley","Dean","Hanson","Garza","Harvey","Little","Burton","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Bishop","Carr","Salazar","Austin","Mendez","Gilbert","Jensen","Williamson","Montgomery","Harvey","Oliver","Howell","Weber","Garrett","Sims","Burton","Fuller","Soto","Mccoy","Welch","Chen","Schultz","Walters","Reid","Fields","Walsh","Little","Fowler","Bowman"]
    }
  },
  // Exotic names = higher chance of being a needle-in-the-haystack recruit
  exotic: {
    first: [],
    last:  []
  }
};